//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 5.0.61118.0
// 
namespace LearnLanguages.DataAccess.WcfProxy.WcfServices.Language {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultOfLanguageDtociihImHl", Namespace="http://schemas.datacontract.org/2004/07/LearnLanguages")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LearnLanguages.DataAccess.LanguageDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<LearnLanguages.DataAccess.LanguageDto>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LearnLanguages.DataAccess.WcfProxy.WcfServices.Language.ResultOfArrayOfLanguageDtociihImHl))]
    public partial class ResultOfLanguageDtociihImHl : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool _IsSuccessField;
        
        private LearnLanguages.MagicStringsList Infok__BackingFieldField;
        
        private string Msgk__BackingFieldField;
        
        private LearnLanguages.DataAccess.LanguageDto Objk__BackingFieldField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool _IsSuccess {
            get {
                return this._IsSuccessField;
            }
            set {
                if ((this._IsSuccessField.Equals(value) != true)) {
                    this._IsSuccessField = value;
                    this.RaisePropertyChanged("_IsSuccess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Info>k__BackingField", IsRequired=true)]
        public LearnLanguages.MagicStringsList Infok__BackingField {
            get {
                return this.Infok__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Infok__BackingFieldField, value) != true)) {
                    this.Infok__BackingFieldField = value;
                    this.RaisePropertyChanged("Infok__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Msg>k__BackingField", IsRequired=true)]
        public string Msgk__BackingField {
            get {
                return this.Msgk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Msgk__BackingFieldField, value) != true)) {
                    this.Msgk__BackingFieldField = value;
                    this.RaisePropertyChanged("Msgk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Obj>k__BackingField", IsRequired=true)]
        public LearnLanguages.DataAccess.LanguageDto Objk__BackingField {
            get {
                return this.Objk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Objk__BackingFieldField, value) != true)) {
                    this.Objk__BackingFieldField = value;
                    this.RaisePropertyChanged("Objk__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultOfArrayOfLanguageDtociihImHl", Namespace="http://schemas.datacontract.org/2004/07/LearnLanguages")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LearnLanguages.DataAccess.LanguageDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<LearnLanguages.DataAccess.LanguageDto>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LearnLanguages.DataAccess.WcfProxy.WcfServices.Language.ResultOfLanguageDtociihImHl))]
    public partial class ResultOfArrayOfLanguageDtociihImHl : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool _IsSuccessField;
        
        private LearnLanguages.MagicStringsList Infok__BackingFieldField;
        
        private string Msgk__BackingFieldField;
        
        private System.Collections.ObjectModel.ObservableCollection<LearnLanguages.DataAccess.LanguageDto> Objk__BackingFieldField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool _IsSuccess {
            get {
                return this._IsSuccessField;
            }
            set {
                if ((this._IsSuccessField.Equals(value) != true)) {
                    this._IsSuccessField = value;
                    this.RaisePropertyChanged("_IsSuccess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Info>k__BackingField", IsRequired=true)]
        public LearnLanguages.MagicStringsList Infok__BackingField {
            get {
                return this.Infok__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Infok__BackingFieldField, value) != true)) {
                    this.Infok__BackingFieldField = value;
                    this.RaisePropertyChanged("Infok__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Msg>k__BackingField", IsRequired=true)]
        public string Msgk__BackingField {
            get {
                return this.Msgk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Msgk__BackingFieldField, value) != true)) {
                    this.Msgk__BackingFieldField = value;
                    this.RaisePropertyChanged("Msgk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Obj>k__BackingField", IsRequired=true)]
        public System.Collections.ObjectModel.ObservableCollection<LearnLanguages.DataAccess.LanguageDto> Objk__BackingField {
            get {
                return this.Objk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Objk__BackingFieldField, value) != true)) {
                    this.Objk__BackingFieldField = value;
                    this.RaisePropertyChanged("Objk__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WcfServices.Language.ILanguageDal")]
    public interface ILanguageDal {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ILanguageDal/New", ReplyAction="http://tempuri.org/ILanguageDal/NewResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(LearnLanguages.DataAccess.LanguageDto))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<LearnLanguages.DataAccess.LanguageDto>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(LearnLanguages.DataAccess.WcfProxy.WcfServices.Language.ResultOfLanguageDtociihImHl))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(LearnLanguages.MagicStringsList))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(LearnLanguages.DataAccess.WcfProxy.WcfServices.Language.ResultOfArrayOfLanguageDtociihImHl))]
        System.IAsyncResult BeginNew(object criteria, System.AsyncCallback callback, object asyncState);
        
        LearnLanguages.DataAccess.WcfProxy.WcfServices.Language.ResultOfLanguageDtociihImHl EndNew(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ILanguageDal/Fetch", ReplyAction="http://tempuri.org/ILanguageDal/FetchResponse")]
        System.IAsyncResult BeginFetch(System.Guid id, System.AsyncCallback callback, object asyncState);
        
        LearnLanguages.DataAccess.WcfProxy.WcfServices.Language.ResultOfLanguageDtociihImHl EndFetch(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ILanguageDal/Update", ReplyAction="http://tempuri.org/ILanguageDal/UpdateResponse")]
        System.IAsyncResult BeginUpdate(LearnLanguages.DataAccess.LanguageDto dto, System.AsyncCallback callback, object asyncState);
        
        LearnLanguages.DataAccess.WcfProxy.WcfServices.Language.ResultOfLanguageDtociihImHl EndUpdate(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ILanguageDal/Insert", ReplyAction="http://tempuri.org/ILanguageDal/InsertResponse")]
        System.IAsyncResult BeginInsert(LearnLanguages.DataAccess.LanguageDto dto, System.AsyncCallback callback, object asyncState);
        
        LearnLanguages.DataAccess.WcfProxy.WcfServices.Language.ResultOfLanguageDtociihImHl EndInsert(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ILanguageDal/Delete", ReplyAction="http://tempuri.org/ILanguageDal/DeleteResponse")]
        System.IAsyncResult BeginDelete(System.Guid id, System.AsyncCallback callback, object asyncState);
        
        LearnLanguages.DataAccess.WcfProxy.WcfServices.Language.ResultOfLanguageDtociihImHl EndDelete(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ILanguageDal/GetAll", ReplyAction="http://tempuri.org/ILanguageDal/GetAllResponse")]
        System.IAsyncResult BeginGetAll(System.AsyncCallback callback, object asyncState);
        
        LearnLanguages.DataAccess.WcfProxy.WcfServices.Language.ResultOfArrayOfLanguageDtociihImHl EndGetAll(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILanguageDalChannel : LearnLanguages.DataAccess.WcfProxy.WcfServices.Language.ILanguageDal, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NewCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public NewCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public LearnLanguages.DataAccess.WcfProxy.WcfServices.Language.ResultOfLanguageDtociihImHl Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((LearnLanguages.DataAccess.WcfProxy.WcfServices.Language.ResultOfLanguageDtociihImHl)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FetchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public FetchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public LearnLanguages.DataAccess.WcfProxy.WcfServices.Language.ResultOfLanguageDtociihImHl Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((LearnLanguages.DataAccess.WcfProxy.WcfServices.Language.ResultOfLanguageDtociihImHl)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UpdateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public UpdateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public LearnLanguages.DataAccess.WcfProxy.WcfServices.Language.ResultOfLanguageDtociihImHl Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((LearnLanguages.DataAccess.WcfProxy.WcfServices.Language.ResultOfLanguageDtociihImHl)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InsertCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public InsertCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public LearnLanguages.DataAccess.WcfProxy.WcfServices.Language.ResultOfLanguageDtociihImHl Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((LearnLanguages.DataAccess.WcfProxy.WcfServices.Language.ResultOfLanguageDtociihImHl)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DeleteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public DeleteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public LearnLanguages.DataAccess.WcfProxy.WcfServices.Language.ResultOfLanguageDtociihImHl Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((LearnLanguages.DataAccess.WcfProxy.WcfServices.Language.ResultOfLanguageDtociihImHl)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetAllCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetAllCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public LearnLanguages.DataAccess.WcfProxy.WcfServices.Language.ResultOfArrayOfLanguageDtociihImHl Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((LearnLanguages.DataAccess.WcfProxy.WcfServices.Language.ResultOfArrayOfLanguageDtociihImHl)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LanguageDalClient : System.ServiceModel.ClientBase<LearnLanguages.DataAccess.WcfProxy.WcfServices.Language.ILanguageDal>, LearnLanguages.DataAccess.WcfProxy.WcfServices.Language.ILanguageDal {
        
        private BeginOperationDelegate onBeginNewDelegate;
        
        private EndOperationDelegate onEndNewDelegate;
        
        private System.Threading.SendOrPostCallback onNewCompletedDelegate;
        
        private BeginOperationDelegate onBeginFetchDelegate;
        
        private EndOperationDelegate onEndFetchDelegate;
        
        private System.Threading.SendOrPostCallback onFetchCompletedDelegate;
        
        private BeginOperationDelegate onBeginUpdateDelegate;
        
        private EndOperationDelegate onEndUpdateDelegate;
        
        private System.Threading.SendOrPostCallback onUpdateCompletedDelegate;
        
        private BeginOperationDelegate onBeginInsertDelegate;
        
        private EndOperationDelegate onEndInsertDelegate;
        
        private System.Threading.SendOrPostCallback onInsertCompletedDelegate;
        
        private BeginOperationDelegate onBeginDeleteDelegate;
        
        private EndOperationDelegate onEndDeleteDelegate;
        
        private System.Threading.SendOrPostCallback onDeleteCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetAllDelegate;
        
        private EndOperationDelegate onEndGetAllDelegate;
        
        private System.Threading.SendOrPostCallback onGetAllCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public LanguageDalClient() {
        }
        
        public LanguageDalClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LanguageDalClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LanguageDalClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LanguageDalClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<NewCompletedEventArgs> NewCompleted;
        
        public event System.EventHandler<FetchCompletedEventArgs> FetchCompleted;
        
        public event System.EventHandler<UpdateCompletedEventArgs> UpdateCompleted;
        
        public event System.EventHandler<InsertCompletedEventArgs> InsertCompleted;
        
        public event System.EventHandler<DeleteCompletedEventArgs> DeleteCompleted;
        
        public event System.EventHandler<GetAllCompletedEventArgs> GetAllCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult LearnLanguages.DataAccess.WcfProxy.WcfServices.Language.ILanguageDal.BeginNew(object criteria, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginNew(criteria, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LearnLanguages.DataAccess.WcfProxy.WcfServices.Language.ResultOfLanguageDtociihImHl LearnLanguages.DataAccess.WcfProxy.WcfServices.Language.ILanguageDal.EndNew(System.IAsyncResult result) {
            return base.Channel.EndNew(result);
        }
        
        private System.IAsyncResult OnBeginNew(object[] inValues, System.AsyncCallback callback, object asyncState) {
            object criteria = ((object)(inValues[0]));
            return ((LearnLanguages.DataAccess.WcfProxy.WcfServices.Language.ILanguageDal)(this)).BeginNew(criteria, callback, asyncState);
        }
        
        private object[] OnEndNew(System.IAsyncResult result) {
            LearnLanguages.DataAccess.WcfProxy.WcfServices.Language.ResultOfLanguageDtociihImHl retVal = ((LearnLanguages.DataAccess.WcfProxy.WcfServices.Language.ILanguageDal)(this)).EndNew(result);
            return new object[] {
                    retVal};
        }
        
        private void OnNewCompleted(object state) {
            if ((this.NewCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.NewCompleted(this, new NewCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void NewAsync(object criteria) {
            this.NewAsync(criteria, null);
        }
        
        public void NewAsync(object criteria, object userState) {
            if ((this.onBeginNewDelegate == null)) {
                this.onBeginNewDelegate = new BeginOperationDelegate(this.OnBeginNew);
            }
            if ((this.onEndNewDelegate == null)) {
                this.onEndNewDelegate = new EndOperationDelegate(this.OnEndNew);
            }
            if ((this.onNewCompletedDelegate == null)) {
                this.onNewCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnNewCompleted);
            }
            base.InvokeAsync(this.onBeginNewDelegate, new object[] {
                        criteria}, this.onEndNewDelegate, this.onNewCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult LearnLanguages.DataAccess.WcfProxy.WcfServices.Language.ILanguageDal.BeginFetch(System.Guid id, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginFetch(id, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LearnLanguages.DataAccess.WcfProxy.WcfServices.Language.ResultOfLanguageDtociihImHl LearnLanguages.DataAccess.WcfProxy.WcfServices.Language.ILanguageDal.EndFetch(System.IAsyncResult result) {
            return base.Channel.EndFetch(result);
        }
        
        private System.IAsyncResult OnBeginFetch(object[] inValues, System.AsyncCallback callback, object asyncState) {
            System.Guid id = ((System.Guid)(inValues[0]));
            return ((LearnLanguages.DataAccess.WcfProxy.WcfServices.Language.ILanguageDal)(this)).BeginFetch(id, callback, asyncState);
        }
        
        private object[] OnEndFetch(System.IAsyncResult result) {
            LearnLanguages.DataAccess.WcfProxy.WcfServices.Language.ResultOfLanguageDtociihImHl retVal = ((LearnLanguages.DataAccess.WcfProxy.WcfServices.Language.ILanguageDal)(this)).EndFetch(result);
            return new object[] {
                    retVal};
        }
        
        private void OnFetchCompleted(object state) {
            if ((this.FetchCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.FetchCompleted(this, new FetchCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void FetchAsync(System.Guid id) {
            this.FetchAsync(id, null);
        }
        
        public void FetchAsync(System.Guid id, object userState) {
            if ((this.onBeginFetchDelegate == null)) {
                this.onBeginFetchDelegate = new BeginOperationDelegate(this.OnBeginFetch);
            }
            if ((this.onEndFetchDelegate == null)) {
                this.onEndFetchDelegate = new EndOperationDelegate(this.OnEndFetch);
            }
            if ((this.onFetchCompletedDelegate == null)) {
                this.onFetchCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnFetchCompleted);
            }
            base.InvokeAsync(this.onBeginFetchDelegate, new object[] {
                        id}, this.onEndFetchDelegate, this.onFetchCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult LearnLanguages.DataAccess.WcfProxy.WcfServices.Language.ILanguageDal.BeginUpdate(LearnLanguages.DataAccess.LanguageDto dto, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginUpdate(dto, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LearnLanguages.DataAccess.WcfProxy.WcfServices.Language.ResultOfLanguageDtociihImHl LearnLanguages.DataAccess.WcfProxy.WcfServices.Language.ILanguageDal.EndUpdate(System.IAsyncResult result) {
            return base.Channel.EndUpdate(result);
        }
        
        private System.IAsyncResult OnBeginUpdate(object[] inValues, System.AsyncCallback callback, object asyncState) {
            LearnLanguages.DataAccess.LanguageDto dto = ((LearnLanguages.DataAccess.LanguageDto)(inValues[0]));
            return ((LearnLanguages.DataAccess.WcfProxy.WcfServices.Language.ILanguageDal)(this)).BeginUpdate(dto, callback, asyncState);
        }
        
        private object[] OnEndUpdate(System.IAsyncResult result) {
            LearnLanguages.DataAccess.WcfProxy.WcfServices.Language.ResultOfLanguageDtociihImHl retVal = ((LearnLanguages.DataAccess.WcfProxy.WcfServices.Language.ILanguageDal)(this)).EndUpdate(result);
            return new object[] {
                    retVal};
        }
        
        private void OnUpdateCompleted(object state) {
            if ((this.UpdateCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.UpdateCompleted(this, new UpdateCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void UpdateAsync(LearnLanguages.DataAccess.LanguageDto dto) {
            this.UpdateAsync(dto, null);
        }
        
        public void UpdateAsync(LearnLanguages.DataAccess.LanguageDto dto, object userState) {
            if ((this.onBeginUpdateDelegate == null)) {
                this.onBeginUpdateDelegate = new BeginOperationDelegate(this.OnBeginUpdate);
            }
            if ((this.onEndUpdateDelegate == null)) {
                this.onEndUpdateDelegate = new EndOperationDelegate(this.OnEndUpdate);
            }
            if ((this.onUpdateCompletedDelegate == null)) {
                this.onUpdateCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnUpdateCompleted);
            }
            base.InvokeAsync(this.onBeginUpdateDelegate, new object[] {
                        dto}, this.onEndUpdateDelegate, this.onUpdateCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult LearnLanguages.DataAccess.WcfProxy.WcfServices.Language.ILanguageDal.BeginInsert(LearnLanguages.DataAccess.LanguageDto dto, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginInsert(dto, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LearnLanguages.DataAccess.WcfProxy.WcfServices.Language.ResultOfLanguageDtociihImHl LearnLanguages.DataAccess.WcfProxy.WcfServices.Language.ILanguageDal.EndInsert(System.IAsyncResult result) {
            return base.Channel.EndInsert(result);
        }
        
        private System.IAsyncResult OnBeginInsert(object[] inValues, System.AsyncCallback callback, object asyncState) {
            LearnLanguages.DataAccess.LanguageDto dto = ((LearnLanguages.DataAccess.LanguageDto)(inValues[0]));
            return ((LearnLanguages.DataAccess.WcfProxy.WcfServices.Language.ILanguageDal)(this)).BeginInsert(dto, callback, asyncState);
        }
        
        private object[] OnEndInsert(System.IAsyncResult result) {
            LearnLanguages.DataAccess.WcfProxy.WcfServices.Language.ResultOfLanguageDtociihImHl retVal = ((LearnLanguages.DataAccess.WcfProxy.WcfServices.Language.ILanguageDal)(this)).EndInsert(result);
            return new object[] {
                    retVal};
        }
        
        private void OnInsertCompleted(object state) {
            if ((this.InsertCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.InsertCompleted(this, new InsertCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void InsertAsync(LearnLanguages.DataAccess.LanguageDto dto) {
            this.InsertAsync(dto, null);
        }
        
        public void InsertAsync(LearnLanguages.DataAccess.LanguageDto dto, object userState) {
            if ((this.onBeginInsertDelegate == null)) {
                this.onBeginInsertDelegate = new BeginOperationDelegate(this.OnBeginInsert);
            }
            if ((this.onEndInsertDelegate == null)) {
                this.onEndInsertDelegate = new EndOperationDelegate(this.OnEndInsert);
            }
            if ((this.onInsertCompletedDelegate == null)) {
                this.onInsertCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnInsertCompleted);
            }
            base.InvokeAsync(this.onBeginInsertDelegate, new object[] {
                        dto}, this.onEndInsertDelegate, this.onInsertCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult LearnLanguages.DataAccess.WcfProxy.WcfServices.Language.ILanguageDal.BeginDelete(System.Guid id, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginDelete(id, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LearnLanguages.DataAccess.WcfProxy.WcfServices.Language.ResultOfLanguageDtociihImHl LearnLanguages.DataAccess.WcfProxy.WcfServices.Language.ILanguageDal.EndDelete(System.IAsyncResult result) {
            return base.Channel.EndDelete(result);
        }
        
        private System.IAsyncResult OnBeginDelete(object[] inValues, System.AsyncCallback callback, object asyncState) {
            System.Guid id = ((System.Guid)(inValues[0]));
            return ((LearnLanguages.DataAccess.WcfProxy.WcfServices.Language.ILanguageDal)(this)).BeginDelete(id, callback, asyncState);
        }
        
        private object[] OnEndDelete(System.IAsyncResult result) {
            LearnLanguages.DataAccess.WcfProxy.WcfServices.Language.ResultOfLanguageDtociihImHl retVal = ((LearnLanguages.DataAccess.WcfProxy.WcfServices.Language.ILanguageDal)(this)).EndDelete(result);
            return new object[] {
                    retVal};
        }
        
        private void OnDeleteCompleted(object state) {
            if ((this.DeleteCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.DeleteCompleted(this, new DeleteCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void DeleteAsync(System.Guid id) {
            this.DeleteAsync(id, null);
        }
        
        public void DeleteAsync(System.Guid id, object userState) {
            if ((this.onBeginDeleteDelegate == null)) {
                this.onBeginDeleteDelegate = new BeginOperationDelegate(this.OnBeginDelete);
            }
            if ((this.onEndDeleteDelegate == null)) {
                this.onEndDeleteDelegate = new EndOperationDelegate(this.OnEndDelete);
            }
            if ((this.onDeleteCompletedDelegate == null)) {
                this.onDeleteCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDeleteCompleted);
            }
            base.InvokeAsync(this.onBeginDeleteDelegate, new object[] {
                        id}, this.onEndDeleteDelegate, this.onDeleteCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult LearnLanguages.DataAccess.WcfProxy.WcfServices.Language.ILanguageDal.BeginGetAll(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetAll(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LearnLanguages.DataAccess.WcfProxy.WcfServices.Language.ResultOfArrayOfLanguageDtociihImHl LearnLanguages.DataAccess.WcfProxy.WcfServices.Language.ILanguageDal.EndGetAll(System.IAsyncResult result) {
            return base.Channel.EndGetAll(result);
        }
        
        private System.IAsyncResult OnBeginGetAll(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((LearnLanguages.DataAccess.WcfProxy.WcfServices.Language.ILanguageDal)(this)).BeginGetAll(callback, asyncState);
        }
        
        private object[] OnEndGetAll(System.IAsyncResult result) {
            LearnLanguages.DataAccess.WcfProxy.WcfServices.Language.ResultOfArrayOfLanguageDtociihImHl retVal = ((LearnLanguages.DataAccess.WcfProxy.WcfServices.Language.ILanguageDal)(this)).EndGetAll(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetAllCompleted(object state) {
            if ((this.GetAllCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetAllCompleted(this, new GetAllCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetAllAsync() {
            this.GetAllAsync(null);
        }
        
        public void GetAllAsync(object userState) {
            if ((this.onBeginGetAllDelegate == null)) {
                this.onBeginGetAllDelegate = new BeginOperationDelegate(this.OnBeginGetAll);
            }
            if ((this.onEndGetAllDelegate == null)) {
                this.onEndGetAllDelegate = new EndOperationDelegate(this.OnEndGetAll);
            }
            if ((this.onGetAllCompletedDelegate == null)) {
                this.onGetAllCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetAllCompleted);
            }
            base.InvokeAsync(this.onBeginGetAllDelegate, null, this.onEndGetAllDelegate, this.onGetAllCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override LearnLanguages.DataAccess.WcfProxy.WcfServices.Language.ILanguageDal CreateChannel() {
            return new LanguageDalClientChannel(this);
        }
        
        private class LanguageDalClientChannel : ChannelBase<LearnLanguages.DataAccess.WcfProxy.WcfServices.Language.ILanguageDal>, LearnLanguages.DataAccess.WcfProxy.WcfServices.Language.ILanguageDal {
            
            public LanguageDalClientChannel(System.ServiceModel.ClientBase<LearnLanguages.DataAccess.WcfProxy.WcfServices.Language.ILanguageDal> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginNew(object criteria, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = criteria;
                System.IAsyncResult _result = base.BeginInvoke("New", _args, callback, asyncState);
                return _result;
            }
            
            public LearnLanguages.DataAccess.WcfProxy.WcfServices.Language.ResultOfLanguageDtociihImHl EndNew(System.IAsyncResult result) {
                object[] _args = new object[0];
                LearnLanguages.DataAccess.WcfProxy.WcfServices.Language.ResultOfLanguageDtociihImHl _result = ((LearnLanguages.DataAccess.WcfProxy.WcfServices.Language.ResultOfLanguageDtociihImHl)(base.EndInvoke("New", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginFetch(System.Guid id, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = id;
                System.IAsyncResult _result = base.BeginInvoke("Fetch", _args, callback, asyncState);
                return _result;
            }
            
            public LearnLanguages.DataAccess.WcfProxy.WcfServices.Language.ResultOfLanguageDtociihImHl EndFetch(System.IAsyncResult result) {
                object[] _args = new object[0];
                LearnLanguages.DataAccess.WcfProxy.WcfServices.Language.ResultOfLanguageDtociihImHl _result = ((LearnLanguages.DataAccess.WcfProxy.WcfServices.Language.ResultOfLanguageDtociihImHl)(base.EndInvoke("Fetch", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginUpdate(LearnLanguages.DataAccess.LanguageDto dto, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = dto;
                System.IAsyncResult _result = base.BeginInvoke("Update", _args, callback, asyncState);
                return _result;
            }
            
            public LearnLanguages.DataAccess.WcfProxy.WcfServices.Language.ResultOfLanguageDtociihImHl EndUpdate(System.IAsyncResult result) {
                object[] _args = new object[0];
                LearnLanguages.DataAccess.WcfProxy.WcfServices.Language.ResultOfLanguageDtociihImHl _result = ((LearnLanguages.DataAccess.WcfProxy.WcfServices.Language.ResultOfLanguageDtociihImHl)(base.EndInvoke("Update", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginInsert(LearnLanguages.DataAccess.LanguageDto dto, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = dto;
                System.IAsyncResult _result = base.BeginInvoke("Insert", _args, callback, asyncState);
                return _result;
            }
            
            public LearnLanguages.DataAccess.WcfProxy.WcfServices.Language.ResultOfLanguageDtociihImHl EndInsert(System.IAsyncResult result) {
                object[] _args = new object[0];
                LearnLanguages.DataAccess.WcfProxy.WcfServices.Language.ResultOfLanguageDtociihImHl _result = ((LearnLanguages.DataAccess.WcfProxy.WcfServices.Language.ResultOfLanguageDtociihImHl)(base.EndInvoke("Insert", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginDelete(System.Guid id, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = id;
                System.IAsyncResult _result = base.BeginInvoke("Delete", _args, callback, asyncState);
                return _result;
            }
            
            public LearnLanguages.DataAccess.WcfProxy.WcfServices.Language.ResultOfLanguageDtociihImHl EndDelete(System.IAsyncResult result) {
                object[] _args = new object[0];
                LearnLanguages.DataAccess.WcfProxy.WcfServices.Language.ResultOfLanguageDtociihImHl _result = ((LearnLanguages.DataAccess.WcfProxy.WcfServices.Language.ResultOfLanguageDtociihImHl)(base.EndInvoke("Delete", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetAll(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetAll", _args, callback, asyncState);
                return _result;
            }
            
            public LearnLanguages.DataAccess.WcfProxy.WcfServices.Language.ResultOfArrayOfLanguageDtociihImHl EndGetAll(System.IAsyncResult result) {
                object[] _args = new object[0];
                LearnLanguages.DataAccess.WcfProxy.WcfServices.Language.ResultOfArrayOfLanguageDtociihImHl _result = ((LearnLanguages.DataAccess.WcfProxy.WcfServices.Language.ResultOfArrayOfLanguageDtociihImHl)(base.EndInvoke("GetAll", _args, result)));
                return _result;
            }
        }
    }
}
