//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.488
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearnLanguages.DataAccess {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DalResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DalResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LearnLanguages.DataAccess.DalResources", typeof(DalResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AllPhrasesList_DalKey.
        /// </summary>
        public static string AllPhrasesList_DalKey {
            get {
                return ResourceManager.GetString("AllPhrasesList_DalKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DalManagerType.
        /// </summary>
        public static string AppSettingsKeyDalManagerTypeName {
            get {
                return ResourceManager.GetString("AppSettingsKeyDalManagerTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string AuthenticationTypeString {
            get {
                return ResourceManager.GetString("AuthenticationTypeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DalSeedDataInitializedKey.
        /// </summary>
        public static string DalSeedDataInitializedKey {
            get {
                return ResourceManager.GetString("DalSeedDataInitializedKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C10D85B4-4DE4-40CB-8ABD-9458AD9B7FD9.
        /// </summary>
        public static string DefaultEnglishLanguageId {
            get {
                return ResourceManager.GetString("DefaultEnglishLanguageId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string DefaultEnglishLanguageText {
            get {
                return ResourceManager.GetString("DefaultEnglishLanguageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C10D85B4-4DE4-40CB-8ABD-9458AD9B7FD9.
        /// </summary>
        public static string DefaultLanguageId {
            get {
                return ResourceManager.GetString("DefaultLanguageId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DefaultNewLanguageText {
            get {
                return ResourceManager.GetString("DefaultNewLanguageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DefaultNewPhraseText {
            get {
                return ResourceManager.GetString("DefaultNewPhraseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DefaultNewPhraseUsername {
            get {
                return ResourceManager.GetString("DefaultNewPhraseUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Create operation failed..
        /// </summary>
        public static string ErrorMsgCreateFailed {
            get {
                return ResourceManager.GetString("ErrorMsgCreateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Delete operation failed..
        /// </summary>
        public static string ErrorMsgDeleteFailed {
            get {
                return ResourceManager.GetString("ErrorMsgDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Delete operation failed.  There were multiple items found to delete..
        /// </summary>
        public static string ErrorMsgDeleteFailed_MultipleItemsFound {
            get {
                return ResourceManager.GetString("ErrorMsgDeleteFailed_MultipleItemsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Fetch operation failed..
        /// </summary>
        public static string ErrorMsgFetchFailed {
            get {
                return ResourceManager.GetString("ErrorMsgFetchFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GeneralDataAccessException.  See Inner Exception for details..
        /// </summary>
        public static string ErrorMsgGeneralDataAccessException {
            get {
                return ResourceManager.GetString("ErrorMsgGeneralDataAccessException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The GetAll operation failed..
        /// </summary>
        public static string ErrorMsgGetAllFailed {
            get {
                return ResourceManager.GetString("ErrorMsgGetAllFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The roles of user ({0}) could not be retrieved..
        /// </summary>
        public static string ErrorMsgGetRolesFailedException {
            get {
                return ResourceManager.GetString("ErrorMsgGetRolesFailedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Id ({0}) already exists..
        /// </summary>
        public static string ErrorMsgIdAlreadyExists {
            get {
                return ResourceManager.GetString("ErrorMsgIdAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Id ({0}) was not found..
        /// </summary>
        public static string ErrorMsgIdNotFound {
            get {
                return ResourceManager.GetString("ErrorMsgIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Insert operation failed..
        /// </summary>
        public static string ErrorMsgInsertFailedException {
            get {
                return ResourceManager.GetString("ErrorMsgInsertFailedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Update operation failed..
        /// </summary>
        public static string ErrorMsgUpdateFailedException {
            get {
                return ResourceManager.GetString("ErrorMsgUpdateFailedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username ({0}) was not found..
        /// </summary>
        public static string ErrorMsgUsernameNotFoundException {
            get {
                return ResourceManager.GetString("ErrorMsgUsernameNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifying the user ({0}) threw an exception..
        /// </summary>
        public static string ErrorMsgVerifyUserFailedException {
            get {
                return ResourceManager.GetString("ErrorMsgVerifyUserFailedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something happened that was very bad. ({0}).
        /// </summary>
        public static string ErrorMsgVeryBadException {
            get {
                return ResourceManager.GetString("ErrorMsgVeryBadException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The result count was anticipated to be either one or zero.  This probably occurred when making a call to the database, expecting a unique result set..
        /// </summary>
        public static string ErrorMsgVeryBadExceptionDetail_ResultCountNotOneOrZero {
            get {
                return ResourceManager.GetString("ErrorMsgVeryBadExceptionDetail_ResultCountNotOneOrZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phrase_DalKey.
        /// </summary>
        public static string Phrase_DalKey {
            get {
                return ResourceManager.GetString("Phrase_DalKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string RoleAdmin {
            get {
                return ResourceManager.GetString("RoleAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string RoleUser {
            get {
                return ResourceManager.GetString("RoleUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://localhost:50094/SlPortal.svc.
        /// </summary>
        public static string WcfProxyDefaultUrl {
            get {
                return ResourceManager.GetString("WcfProxyDefaultUrl", resourceCulture);
            }
        }
    }
}
