//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.488
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearnLanguages.DataAccess {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DalResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DalResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LearnLanguages.DataAccess.DalResources", typeof(DalResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AllPhrasesList_DalKey.
        /// </summary>
        public static string AllPhrasesList_DalKey {
            get {
                return ResourceManager.GetString("AllPhrasesList_DalKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DalManagerType.
        /// </summary>
        public static string AppSettingsKeyDalManagerTypeName {
            get {
                return ResourceManager.GetString("AppSettingsKeyDalManagerTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C10D85B4-4DE4-40CB-8ABD-9458AD9B7FD9.
        /// </summary>
        public static string DefaultEnglishLanguageId {
            get {
                return ResourceManager.GetString("DefaultEnglishLanguageId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string DefaultEnglishLanguageText {
            get {
                return ResourceManager.GetString("DefaultEnglishLanguageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C10D85B4-4DE4-40CB-8ABD-9458AD9B7FD9.
        /// </summary>
        public static string DefaultLanguageId {
            get {
                return ResourceManager.GetString("DefaultLanguageId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DefaultNewLanguageText {
            get {
                return ResourceManager.GetString("DefaultNewLanguageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DefaultNewPhraseText {
            get {
                return ResourceManager.GetString("DefaultNewPhraseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Create operation failed..
        /// </summary>
        public static string ErrorMsgCreateFailed {
            get {
                return ResourceManager.GetString("ErrorMsgCreateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Delete operation failed..
        /// </summary>
        public static string ErrorMsgDeleteFailed {
            get {
                return ResourceManager.GetString("ErrorMsgDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Delete operation failed.  There were multiple items found to delete..
        /// </summary>
        public static string ErrorMsgDeleteFailed_MultipleItemsFound {
            get {
                return ResourceManager.GetString("ErrorMsgDeleteFailed_MultipleItemsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Fetch operation failed..
        /// </summary>
        public static string ErrorMsgFetchFailed {
            get {
                return ResourceManager.GetString("ErrorMsgFetchFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Id was not found..
        /// </summary>
        public static string ErrorMsgIdNotFound {
            get {
                return ResourceManager.GetString("ErrorMsgIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Insert operation failed..
        /// </summary>
        public static string ErrorMsgInsertFailed {
            get {
                return ResourceManager.GetString("ErrorMsgInsertFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Insert operation failed.  The Id {0} already exists..
        /// </summary>
        public static string ErrorMsgInsertFailed_IdAlreadyExists {
            get {
                return ResourceManager.GetString("ErrorMsgInsertFailed_IdAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid LanguageId in Phrase.  This must be a valid Id in the Languages database..
        /// </summary>
        public static string ErrorMsgInsertFailedPhraseInvalidLanguageId {
            get {
                return ResourceManager.GetString("ErrorMsgInsertFailedPhraseInvalidLanguageId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Save operation failed..
        /// </summary>
        public static string ErrorMsgSaveFailed {
            get {
                return ResourceManager.GetString("ErrorMsgSaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Update operation failed..
        /// </summary>
        public static string ErrorMsgUpdateFailed {
            get {
                return ResourceManager.GetString("ErrorMsgUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phrase_DalKey.
        /// </summary>
        public static string Phrase_DalKey {
            get {
                return ResourceManager.GetString("Phrase_DalKey", resourceCulture);
            }
        }
    }
}
