//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.488
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearnLanguages.DataAccess {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DalResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DalResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LearnLanguages.DataAccess.DalResources", typeof(DalResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AllPhrasesList_DalKey.
        /// </summary>
        public static string AllPhrasesList_DalKey {
            get {
                return ResourceManager.GetString("AllPhrasesList_DalKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DalManagerType.
        /// </summary>
        public static string AppSettingsKeyDalManagerTypeName {
            get {
                return ResourceManager.GetString("AppSettingsKeyDalManagerTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Create operation failed..
        /// </summary>
        public static string Dal_CreateFailedErrorMessage {
            get {
                return ResourceManager.GetString("Dal_CreateFailedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Delete operation failed..
        /// </summary>
        public static string Dal_DeleteFailedErrorMessage {
            get {
                return ResourceManager.GetString("Dal_DeleteFailedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Delete operation failed.  There were multiple items found to delete..
        /// </summary>
        public static string Dal_DeleteFailedErrorMessage_MultipleItemsFound {
            get {
                return ResourceManager.GetString("Dal_DeleteFailedErrorMessage_MultipleItemsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Fetch operation failed..
        /// </summary>
        public static string Dal_FetchFailedErrorMessage {
            get {
                return ResourceManager.GetString("Dal_FetchFailedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Id was not found..
        /// </summary>
        public static string Dal_IdNotFound {
            get {
                return ResourceManager.GetString("Dal_IdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Insert operation failed..
        /// </summary>
        public static string Dal_InsertFailedErrorMessage {
            get {
                return ResourceManager.GetString("Dal_InsertFailedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Insert operation failed.  The Id {0} already exists..
        /// </summary>
        public static string Dal_InsertFailedErrorMessage_IdAlreadyExists {
            get {
                return ResourceManager.GetString("Dal_InsertFailedErrorMessage_IdAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Save operation failed..
        /// </summary>
        public static string Dal_SaveFailedErrorMessage {
            get {
                return ResourceManager.GetString("Dal_SaveFailedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Update operation failed..
        /// </summary>
        public static string Dal_UpdateFailedErrorMessage {
            get {
                return ResourceManager.GetString("Dal_UpdateFailedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phrase_DalKey.
        /// </summary>
        public static string Phrase_DalKey {
            get {
                return ResourceManager.GetString("Phrase_DalKey", resourceCulture);
            }
        }
    }
}
