// <auto-generated />
namespace LearnLanguages.DataAccess.EFCodeFirst.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class InitialMigration : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201201091440273_InitialMigration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAOy9B2AcSZYlJi9tynt/SvVK1+B0oQiAYBMk2JBAEOzBiM3mkuwdaUcjKasqgcplVmVdZhZAzO2dvPfee++999577733ujudTif33/8/XGZkAWz2zkrayZ4hgKrIHz9+fB8/Iv7Hv/cffPx7vFuU6WVeN0W1/Oyj3fHOR2m+nFazYnnx2Ufr9nz74KPf4+g3Th6fzhbv0p807fbQjt5cNp99NG/b1aO7d5vpPF9kzXhRTOuqqc7b8bRa3M1m1d29nZ2Du7s7d3MC8RHBStPHr9bLtljk/Af9eVItp/mqXWflF9UsLxv9nL55zVDTF9kib1bZNP/so+d5Vi+fZ8uLdXaRN+OnWZsdT6d504xPn53Q28+Kumk/So/LIiPkXufl+XtiuvMQmH5kcSAsTgnb9vrN9SpnTD776OW8zpr8aVv5zajh75VfBx/QRy/rapXX7fWr/FxfPpt9lN4N37vbfdG+5r2D/j/76PN1Qb+/WJdlNinp7/OsbPIewM7rb/J3rQHwuq1pcj9KnxXv8tnzfHnRzi2UL7J35hP69aP0q2VBvEAvtfU693uVvzd3aibpvXB/fNcRe+MUGOg/moRbU4/ErM2KZV4bEgaihG+BYTgGefN13gac33yUuo5EysZOJrp06MKwXUag+NMaHZodhFMSd0VLGG1yd0CdPP4iW62I6p560U/S16JbTrZfv7+yWAiMu9MmojMstrantqppeJ1vqWujuqDQJhn44GS26DV7rykzfYYz15UNNwWmPX6PcciAsvVmvgPbUfgZDXqRL1sev46eMBzUpPr262lWZnVEDE+qcr1YDonyprdFCv335ZPbQ/D1mg/H/7wP7fHdDim68+CJrrbsqKfuvN5q1p2sffPzPqiCGf5NM7/x7Z/ruf9Zna2eKus2sb1bldZRXY9VjdzsLvX0ijT5KCXSXBYz6JTX102bL3iSx69/UXlSFjRe1+CLbFmc5037pnqbw/Ujtff13auHd3f24F7dbZpZ+f9aH2u9LH7ROqfBE07nRV5/kKlfXmb1dJ7VW4vs3Z0P96HeE7f/b/hT7zmob4zg7+cv9W30gArucfBGb0kk8rOPZhP6442gar+Gk3RLdyreUfBtrCuvQbez9/C5+grp8V0/ynv8NG+KCwcCMd8yn7YUTjqgps3Z8rwyE0zj9DEyTTrz/0XeZjNYqZoYKJu29DXMVQEf+yezck1NTheTfHa2/HLdrtbtcdPki0l57Y/38d3N/bNjGeL8+MsV/vI08NcfAqFZ0BDyL5dP1kU5s3g/iwj1AAgw6Oc5fZ4BK4oxCNzFtYX0olreEpCS72m+ypcQyjf5YlUSsObL5evsMh/G7WYahhR7/LTILups4VNQPlFMXmfUs9cFdeC/4fqjP4ldKcVw9P8EAAD//0xBh47XEAAA"; }
        }
    }
}
