//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.530
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearnLanguages.History {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HistoryResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HistoryResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LearnLanguages.History.HistoryResources", typeof(HistoryResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An event has occurred in the incorrect order.  E.g. Feedback has been given before an event to produce feedback has occurred..
        /// </summary>
        internal static string ErrorMsgSagaMessageIncorrectOrder {
            get {
                return ResourceManager.GetString("ErrorMsgSagaMessageIncorrectOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 59FD150A-92BB-4130-A427-2AFF9434B748.
        /// </summary>
        internal static string HistoryPublisherId {
            get {
                return ResourceManager.GetString("HistoryPublisherId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChildId.
        /// </summary>
        internal static string Key_ChildId {
            get {
                return ResourceManager.GetString("Key_ChildId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FeedbackAsDouble.
        /// </summary>
        internal static string Key_FeedbackAsDouble {
            get {
                return ResourceManager.GetString("Key_FeedbackAsDouble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LanguageId.
        /// </summary>
        internal static string Key_LanguageId {
            get {
                return ResourceManager.GetString("Key_LanguageId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LanguageText.
        /// </summary>
        internal static string Key_LanguageText {
            get {
                return ResourceManager.GetString("Key_LanguageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LineId.
        /// </summary>
        internal static string Key_LineId {
            get {
                return ResourceManager.GetString("Key_LineId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LineNumber.
        /// </summary>
        internal static string Key_LineNumber {
            get {
                return ResourceManager.GetString("Key_LineNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LineText.
        /// </summary>
        internal static string Key_LineText {
            get {
                return ResourceManager.GetString("Key_LineText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ParentId.
        /// </summary>
        internal static string Key_ParentId {
            get {
                return ResourceManager.GetString("Key_ParentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhraseId.
        /// </summary>
        internal static string Key_PhraseId {
            get {
                return ResourceManager.GetString("Key_PhraseId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhraseText.
        /// </summary>
        internal static string Key_PhraseText {
            get {
                return ResourceManager.GetString("Key_PhraseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReviewMethodId.
        /// </summary>
        internal static string Key_ReviewMethodId {
            get {
                return ResourceManager.GetString("Key_ReviewMethodId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TargetId.
        /// </summary>
        internal static string Key_TargetId {
            get {
                return ResourceManager.GetString("Key_TargetId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TargetType.
        /// </summary>
        internal static string Key_TargetType {
            get {
                return ResourceManager.GetString("Key_TargetType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        internal static string Key_TargetTypeLine {
            get {
                return ResourceManager.GetString("Key_TargetTypeLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MultiLineText.
        /// </summary>
        internal static string Key_TargetTypeMultiLineText {
            get {
                return ResourceManager.GetString("Key_TargetTypeMultiLineText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phrase.
        /// </summary>
        internal static string Key_TargetTypePhrase {
            get {
                return ResourceManager.GetString("Key_TargetTypePhrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhraseCreatedFromScratch.
        /// </summary>
        internal static string TextPhraseCreatedFromScratch {
            get {
                return ResourceManager.GetString("TextPhraseCreatedFromScratch", resourceCulture);
            }
        }
    }
}
