//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearnLanguages.Silverlight.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ViewViewModelResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ViewViewModelResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LearnLanguages.Silverlight.Common.ViewViewModelResources", typeof(ViewViewModelResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AutoTitlePrefix {
            get {
                return ResourceManager.GetString("AutoTitlePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        public static string DefaultPercentKnown {
            get {
                return ResourceManager.GetString("DefaultPercentKnown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new song in whatever language you want..
        /// </summary>
        public static string DescriptionAddSongPage {
            get {
                return ResourceManager.GetString("DescriptionAddSongPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is your Homeeee Pageeeee!.
        /// </summary>
        public static string DescriptionHomePage {
            get {
                return ResourceManager.GetString("DescriptionHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This page is where you can login to your account..
        /// </summary>
        public static string DescriptionLoginPage {
            get {
                return ResourceManager.GetString("DescriptionLoginPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Optional) Add additional info about the song here.  This is still under construction though!!.
        /// </summary>
        public static string InstructionsAddSongEnterSongAdditionalMetadata {
            get {
                return ResourceManager.GetString("InstructionsAddSongEnterSongAdditionalMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the entire lyrics to the song, starting with the name of the song and artist on the first two lines.  If you don&apos;t know these, it&apos;s okay - no big.  Be sure to enter the lyrics line by line as you would want to learn them..
        /// </summary>
        public static string InstructionsAddSongEnterSongText {
            get {
                return ResourceManager.GetString("InstructionsAddSongEnterSongText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Optional) Enter the song&apos;s title here.  If you do not provide one, then the first line will act as the song&apos;s title..
        /// </summary>
        public static string InstructionsAddSongEnterSongTitle {
            get {
                return ResourceManager.GetString("InstructionsAddSongEnterSongTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding a song is extremely easy.  Just select the language the song is in, optionally put in the song title and additional info, and then enter the entire lyrics of the song.  Once you are done, click &quot;Save&quot;.  (Hint: You can also hold the mouse over any control for a tooltip on that control.).
        /// </summary>
        public static string InstructionsAddSongPage {
            get {
                return ResourceManager.GetString("InstructionsAddSongPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the language of the song.  If it is not in the list, click &quot;Add Language&quot; first, then select the newly added language..
        /// </summary>
        public static string InstructionsAddSongSelectLanguage {
            get {
                return ResourceManager.GetString("InstructionsAddSongSelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select how much of this phrase do you know in the targeted language.  If you know it completely, select 100%.  If you don&apos;t know it at all, select 0%.  If you know somewhere in between, estimate to the best of your ability how much of the translation  you know in the targeted language..
        /// </summary>
        public static string InstructionsAskHowMuchDoYouKnowResponse {
            get {
                return ResourceManager.GetString("InstructionsAskHowMuchDoYouKnowResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter as much text as you want to learn.  We will divide this into smaller phrases and words as we go.
        ///
        ///(If you want to add a song, however, &quot;Add Song&quot; is recommended for learning line order.).
        /// </summary>
        public static string InstructionsEnterPhrase {
            get {
                return ResourceManager.GetString("InstructionsEnterPhrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Be at home on your Home Page..
        /// </summary>
        public static string InstructionsHomePage {
            get {
                return ResourceManager.GetString("InstructionsHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your username and password..
        /// </summary>
        public static string InstructionsLoginPage {
            get {
                return ResourceManager.GetString("InstructionsLoginPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Language.
        /// </summary>
        public static string InstructionsSelectLanguage {
            get {
                return ResourceManager.GetString("InstructionsSelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string LabelAcceptPercentKnown {
            get {
                return ResourceManager.GetString("LabelAcceptPercentKnown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language: .
        /// </summary>
        public static string LabelAddLanguageLanguageText {
            get {
                return ResourceManager.GetString("LabelAddLanguageLanguageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language: .
        /// </summary>
        public static string LabelAddPhraseLanguageText {
            get {
                return ResourceManager.GetString("LabelAddPhraseLanguageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phrase: .
        /// </summary>
        public static string LabelAddPhrasePhraseText {
            get {
                return ResourceManager.GetString("LabelAddPhrasePhraseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song Language: .
        /// </summary>
        public static string LabelAddSongLanguage {
            get {
                return ResourceManager.GetString("LabelAddSongLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song Lyrics: .
        /// </summary>
        public static string LabelAddSongSongText {
            get {
                return ResourceManager.GetString("LabelAddSongSongText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song Title: .
        /// </summary>
        public static string LabelAddSongSongTitle {
            get {
                return ResourceManager.GetString("LabelAddSongSongTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song Text: .
        /// </summary>
        public static string LabelAddSongText {
            get {
                return ResourceManager.GetString("LabelAddSongText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string LabelSaveButton {
            get {
                return ResourceManager.GetString("LabelSaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song Info: .
        /// </summary>
        public static string LabelSongAdditionalMetadata {
            get {
                return ResourceManager.GetString("LabelSongAdditionalMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 400.
        /// </summary>
        public static string MaxInstructionsWidth {
            get {
                return ResourceManager.GetString("MaxInstructionsWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        public static string MaxThinkingDots {
            get {
                return ResourceManager.GetString("MaxThinkingDots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Username ({0}) was successfully added..
        /// </summary>
        public static string MessageNewUserAdded {
            get {
                return ResourceManager.GetString("MessageNewUserAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string NavButtonTextLogin {
            get {
                return ResourceManager.GetString("NavButtonTextLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string NavButtonTextLogout {
            get {
                return ResourceManager.GetString("NavButtonTextLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        public static string NavSetTextAddSong {
            get {
                return ResourceManager.GetString("NavSetTextAddSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string NavSetTextGeneral {
            get {
                return ResourceManager.GetString("NavSetTextGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string NavSetTextHome {
            get {
                return ResourceManager.GetString("NavSetTextHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add A Song.
        /// </summary>
        public static string NavTextAddSongPage {
            get {
                return ResourceManager.GetString("NavTextAddSongPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string NavTextHomePage {
            get {
                return ResourceManager.GetString("NavTextHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string NavTextLoginPage {
            get {
                return ResourceManager.GetString("NavTextLoginPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True.
        /// </summary>
        public static string ShowGridLines {
            get {
                return ResourceManager.GetString("ShowGridLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True.
        /// </summary>
        public static string ShowInstructions {
            get {
                return ResourceManager.GetString("ShowInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        public static string SortOrderAddSongPage {
            get {
                return ResourceManager.GetString("SortOrderAddSongPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string SortOrderHomePage {
            get {
                return ResourceManager.GetString("SortOrderHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        public static string SortOrderLoginPage {
            get {
                return ResourceManager.GetString("SortOrderLoginPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Language.
        /// </summary>
        public static string TitleAddLanguage {
            get {
                return ResourceManager.GetString("TitleAddLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add A Song.
        /// </summary>
        public static string TitleAddSongPage {
            get {
                return ResourceManager.GetString("TitleAddSongPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string TitleHomePage {
            get {
                return ResourceManager.GetString("TitleHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string TitleLoginPage {
            get {
                return ResourceManager.GetString("TitleLoginPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the song in the box, line by line..
        /// </summary>
        public static string ToolTipAddSongPage {
            get {
                return ResourceManager.GetString("ToolTipAddSongPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome Home!.
        /// </summary>
        public static string ToolTipHomePage {
            get {
                return ResourceManager.GetString("ToolTipHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your username and password..
        /// </summary>
        public static string ToolTipLoginPage {
            get {
                return ResourceManager.GetString("ToolTipLoginPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Language.
        /// </summary>
        public static string ToolTipTextAddLanguage {
            get {
                return ResourceManager.GetString("ToolTipTextAddLanguage", resourceCulture);
            }
        }
    }
}
