//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.488
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearnLanguages.Silverlight {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ViewViewModelResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ViewViewModelResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LearnLanguages.Silverlight.ViewViewModelResources", typeof(ViewViewModelResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        public static string DefaultPercentKnown {
            get {
                return ResourceManager.GetString("DefaultPercentKnown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select how much of this phrase do you know in the targeted language.  If you know it completely, select 100%.  If you don&apos;t know it at all, select 0%.  If you know somewhere in between, estimate to the best of your ability how much of the translation  you know in the targeted language..
        /// </summary>
        public static string InstructionsAskHowMuchDoYouKnowResponse {
            get {
                return ResourceManager.GetString("InstructionsAskHowMuchDoYouKnowResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 2: Enter as much text as you want to learn, like an original poem, song lyrics, story, vocabulary list, etc.  We will divide this into smaller phrases and words as we go..
        /// </summary>
        public static string InstructionsEnterPhrase {
            get {
                return ResourceManager.GetString("InstructionsEnterPhrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 2: Enter the entire lyrics to the song, starting with the name of the song and artist on the first two lines.  If you don&apos;t know these, it&apos;s okay - no big.  Be sure to enter the lyrics line by line as you would want to learn them..
        /// </summary>
        public static string InstructionsEnterPhraseIWantToLearnASong {
            get {
                return ResourceManager.GetString("InstructionsEnterPhraseIWantToLearnASong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 1: Select Language.
        /// </summary>
        public static string InstructionsSelectLanguage {
            get {
                return ResourceManager.GetString("InstructionsSelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 1: Select the language of the song.  If it is not in the list, click &quot;Add Language&quot; first..
        /// </summary>
        public static string InstructionsSelectLanguageIWantToLearnASong {
            get {
                return ResourceManager.GetString("InstructionsSelectLanguageIWantToLearnASong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string LabelAcceptPercentKnown {
            get {
                return ResourceManager.GetString("LabelAcceptPercentKnown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language: .
        /// </summary>
        public static string LabelAddLanguageViewLanguageText {
            get {
                return ResourceManager.GetString("LabelAddLanguageViewLanguageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language: .
        /// </summary>
        public static string LabelAddPhraseViewLanguageText {
            get {
                return ResourceManager.GetString("LabelAddPhraseViewLanguageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phrase: .
        /// </summary>
        public static string LabelAddPhraseViewPhraseText {
            get {
                return ResourceManager.GetString("LabelAddPhraseViewPhraseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language: .
        /// </summary>
        public static string LabelLanguageTextIWantToLearnASongView {
            get {
                return ResourceManager.GetString("LabelLanguageTextIWantToLearnASongView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phrase: .
        /// </summary>
        public static string LabelPhraseTextIWantToLearnASongView {
            get {
                return ResourceManager.GetString("LabelPhraseTextIWantToLearnASongView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \r.
        /// </summary>
        public static string LineDelimiter {
            get {
                return ResourceManager.GetString("LineDelimiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 400.
        /// </summary>
        public static string MaxInstructionsWidth {
            get {
                return ResourceManager.GetString("MaxInstructionsWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\W+.
        /// </summary>
        public static string RegExSplitPatternWords {
            get {
                return ResourceManager.GetString("RegExSplitPatternWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True.
        /// </summary>
        public static string ShowInstructions {
            get {
                return ResourceManager.GetString("ShowInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Language.
        /// </summary>
        public static string ToolTipTextAddLanguage {
            get {
                return ResourceManager.GetString("ToolTipTextAddLanguage", resourceCulture);
            }
        }
    }
}
