//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.488
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearnLanguages.Study {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StudyResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StudyResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LearnLanguages.Study.StudyResources", typeof(StudyResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Study.
        /// </summary>
        public static string CategoryStudy {
            get {
                return ResourceManager.GetString("CategoryStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10000.
        /// </summary>
        public static string DefaultAmountDefaultMultiLineTextsStudier {
            get {
                return ResourceManager.GetString("DefaultAmountDefaultMultiLineTextsStudier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1000.
        /// </summary>
        public static string DefaultAmountDefaultPhraseMeaningStudier {
            get {
                return ResourceManager.GetString("DefaultAmountDefaultPhraseMeaningStudier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 200.
        /// </summary>
        public static string DefaultFeedbackCheckIntervalMilliseconds {
            get {
                return ResourceManager.GetString("DefaultFeedbackCheckIntervalMilliseconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10000.
        /// </summary>
        public static string DefaultFeedbackTimeoutMilliseconds {
            get {
                return ResourceManager.GetString("DefaultFeedbackTimeoutMilliseconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 85.
        /// </summary>
        public static string DefaultKnowledgeThreshold {
            get {
                return ResourceManager.GetString("DefaultKnowledgeThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100.
        /// </summary>
        public static string DefaultMaxIterationsAggregateAdjacentKnownPhraseTexts {
            get {
                return ResourceManager.GetString("DefaultMaxIterationsAggregateAdjacentKnownPhraseTexts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        public static string DefaultMeaningStudierActiveLinesCount {
            get {
                return ResourceManager.GetString("DefaultMeaningStudierActiveLinesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        public static string DefaultMeaningStudierAggregateSize {
            get {
                return ResourceManager.GetString("DefaultMeaningStudierAggregateSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        public static string DefaultMultiLineTextsStudierMeaningWeight {
            get {
                return ResourceManager.GetString("DefaultMultiLineTextsStudierMeaningWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string DefaultMultiLineTextsStudierOrderWeight {
            get {
                return ResourceManager.GetString("DefaultMultiLineTextsStudierOrderWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 92A7E7C6-8278-4142-A962-6616E2959D1C.
        /// </summary>
        public static string DefaultOfferExchangeId {
            get {
                return ResourceManager.GetString("DefaultOfferExchangeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1000.
        /// </summary>
        public static string DefaultStudyHeartbeatTimeMilliseconds {
            get {
                return ResourceManager.GetString("DefaultStudyHeartbeatTimeMilliseconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Study Ya ya ya!.
        /// </summary>
        public static string DefaultStudyTitle {
            get {
                return ResourceManager.GetString("DefaultStudyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5000.
        /// </summary>
        public static string DefaultThinkAboutAnswerTime {
            get {
                return ResourceManager.GetString("DefaultThinkAboutAnswerTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The answer is null..
        /// </summary>
        public static string ErrorMsgAnswerIsNull {
            get {
                return ResourceManager.GetString("ErrorMsgAnswerIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The language is null..
        /// </summary>
        public static string ErrorMsgLanguageIsNull {
            get {
                return ResourceManager.GetString("ErrorMsgLanguageIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Language.Text is null or empty..
        /// </summary>
        public static string ErrorMsgLanguageTextIsNullOrEmpty {
            get {
                return ResourceManager.GetString("ErrorMsgLanguageTextIsNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The question is null..
        /// </summary>
        public static string ErrorMsgQuestionIsNull {
            get {
                return ResourceManager.GetString("ErrorMsgQuestionIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception was thrown during study.  See inner exception for details..
        /// </summary>
        public static string ErrorMsgStudyException {
            get {
                return ResourceManager.GetString("ErrorMsgStudyException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To continue learning, click Next.  Choose your feedback.  More instructions here......
        /// </summary>
        public static string InstructionsDefaultStudyPartner {
            get {
                return ResourceManager.GetString("InstructionsDefaultStudyPartner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You know this item completely. (95%-100%).
        /// </summary>
        public static string InstructionsSelectFeedbackAll {
            get {
                return ResourceManager.GetString("InstructionsSelectFeedbackAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You know the majority of this item.  (50%-95%).
        /// </summary>
        public static string InstructionsSelectFeedbackMost {
            get {
                return ResourceManager.GetString("InstructionsSelectFeedbackMost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You hardly know this item at all.  (0%-5%).
        /// </summary>
        public static string InstructionsSelectFeedbackNone {
            get {
                return ResourceManager.GetString("InstructionsSelectFeedbackNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the amount of knowledge you have of the given item.  Approximate to the best of your ability!.
        /// </summary>
        public static string InstructionsSelectFeedbackNoneSomeMostAll {
            get {
                return ResourceManager.GetString("InstructionsSelectFeedbackNoneSomeMostAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You know a little, or even perhaps, a decent amount of this item. (5%-50%).
        /// </summary>
        public static string InstructionsSelectFeedbackSome {
            get {
                return ResourceManager.GetString("InstructionsSelectFeedbackSome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100.
        /// </summary>
        public static string PercentKnownAll {
            get {
                return ResourceManager.GetString("PercentKnownAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 75.
        /// </summary>
        public static string PercentKnownMost {
            get {
                return ResourceManager.GetString("PercentKnownMost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string PercentKnownNone {
            get {
                return ResourceManager.GetString("PercentKnownNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 25.
        /// </summary>
        public static string PercentKnownSome {
            get {
                return ResourceManager.GetString("PercentKnownSome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meaning.
        /// </summary>
        public static string StudyContextMeaning {
            get {
                return ResourceManager.GetString("StudyContextMeaning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string StudyContextOrder {
            get {
                return ResourceManager.GetString("StudyContextOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string StudyContextTotal {
            get {
                return ResourceManager.GetString("StudyContextTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An empty phrase text was found in AggregatePhraseTexts.  This shouldn&apos;t happen..
        /// </summary>
        public static string WarningMsgEmptyAggregatePhraseTextFound {
            get {
                return ResourceManager.GetString("WarningMsgEmptyAggregatePhraseTextFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown offer response ({0}) was given..
        /// </summary>
        public static string WarningMsgUnknownOfferResponseResponse {
            get {
                return ResourceManager.GetString("WarningMsgUnknownOfferResponseResponse", resourceCulture);
            }
        }
    }
}
